MetaMask/action-create-release-pr

dist/index.js, package.json, src/git-operations.test.ts, src/git-operations.ts, src/package-operations.test.ts, src/package-operations.ts, src/update.test.ts, src/update.ts, yarn.lock
The `workspaces` property in `package.json` is now used to find workspaces. Previously it was assumed that packages were in the directory 'packages'.
The package `glob` has been added to parse the `workspaces` entries. This is the package [that Yarn itself uses](https://github.com/yarnpkg/yarn/blob/3119382885ea373d3c13d6a846de743eca8c914b/src/config.js#L821), so it should work well enough here.
As part of this change, the `dirPath` property in the package metadata we pass around has been changed to represent the package path relative to the root directory. Previously it was the either absolute or relative to the current working directory. This was easier, and it let us delete the utility that was used for shortening the path to a readable length (which was itself assuming the use of a …
=> Use `workspaces` manifest entry to find workspaces

.github/workflows/build-lint-test.yml, .yarnrc, README.md, package.json, yarn.lock
`@lavamoat/allow-scripts` is now used to selectively run post-install scripts. A `.yarnrc` file has been added to prevent scripts from running during the normal install command.
A "Contributing" section has been added to the README to explain how to install dependencies, along with other standard setup instructions. I noticed that test and lint instructions were missing as well, so those have been added to fill out this new section.
=> Add `@lavamoat/allow-scripts` and `setup` command

README.md, package.json
The `engines` entry that requires the use of Yarn v1 has been removed. I suspect this is compatible with both npm and Yarn v2, but we haven't tested this. Just in case we're wrong, the README has been updated to say that we only test this with Yarn v1
=> Remove package manager restriction

dist/index.js, src/git-operations.test.ts, src/git-operations.ts
This PR fixes `git diff`:ing packages in monorepos. We broke this in #20 such that the `hasDiff` function would always return `true` if any file had change relative to the specified git tag. A test case has been added that fails on current `main`.
=> Fix monorepo package diffing

scripts/create-release-pr.sh
Since we're using the prefix of branch names created by this Action to trigger `action-publish-release`, it seems useful to ensure that we will _never_ in practice manually create a branch whose name collides with said prefix. Usually, branch names at MetaMask are snake-case, and at times contain forward slashes (`/`). Rarely if ever do we use underscores. Therefore, prefixing automation-related branch names with `automation_` seems like a dependable way to distinguish them from "regular" branches.
Since the branches created by this Action are intended to be version-tagged and published as GitHub releases, creating branches named `automation_release-<version>`, where `<version>` is a plain, un-prefixed SemVer version (e.g. `1.0.0`), seems like a good solution.
=> Change release branch prefix from 'release-v' to 'release/'

README.md, action.yml, scripts/create-release-pr.sh
Adds a branch prefix input, so that the release branch prefix is configurable for both this Action and `action-publish-release`.
=> Add release branch prefix input

scripts/create-release-pr.sh
Removes the ` RC`-suffix from the PR title, making it just the SemVer version.
=> Remove ' RC' suffix from PR title

.github/workflows/create-release-pr.yml
Uses this local version of this action in the `create-release-pr` workflow.
=> Use local version of Action for create-release-pr workflow

.github/workflows/publish-release.yml
I forgot to update the input to `publish-release`.
=> Fix release branch prefix input in local workflow

.github/workflows/publish-release.yml, scripts/update-major-version-tag.sh
Automate the updating of the shorthand major version tag (e.g. `v1`) at the end of the `publish-release` workflow. To facilitate updating this tag, `actions/checkout` now fetches the entire git history. We also set the base branch for all git operations in that workflow to the release pull request base branch, so that we can release branches other than `main`.
While we're here, also removes an input to the `publish-release` action in that workflow that is no longer necessary under the new versioning scheme.
=> Automate shorthand major version tag updating

.github/workflows/publish-release.yml
Document why we fetch the complete git history in the `publish-release` workflow.
=> Improve local workflow documentation

dist/index.js, src/index.test.ts, src/index.ts
The `setFailed` function of `@actions/core` only logs `error.toString()`, which doesn't include the error stack trace. This PR adds a call to the `error` function of that package. We could use `debug`, but then you have to add a repository secret to enable debug logging. This log should always be visible. See the package website for details: https://www.npmjs.com/package/@actions/core
=> Add debug logging

README.md
Maintainers must make some changes to any new packages they add to a monorepo with previously released packages. This RP documents these changes in the readme.
=> Add instructions for adding new packages to monorepos

dist/index.js, src/update.test.ts, src/update.ts
Monorepo package versions should always be synchronized if the major version is zero, because any bump within major version zero can be breaking per SemVer conventions.
=> Synchronize monorepo packages for versions in range ^0.x.x

package.json, tsconfig.build.json, tsconfig.json
These changes are copied from the [module template][1]. The main goal
here is to expand TypeScript's purview so that it includes test files,
improving the overall development experience. We also remove `typeRoots`
from the config (because the value provided is already the default) and
add `exclude`s in the default `tsconfig.json` (for consistency with the
module template).
[1]: https://github.com/MetaMask/metamask-module-template/pull/102
=> Create build-only tsconfig

dist/index.js, jest.config.js, package.json, yarn.lock
Because Jest no longer uses Jasmine, but its own custom test runner
called Circus, this fixes a bug in Jest where if an error occurs in a
`beforeAll` hook it does not prevent the tests that make use of the hook
from running.
This commit also bumps `ts-jest`, which compels us to bump TypeScript as
well.
[1]: https://github.com/facebook/jest/issues/2713
=> Bump Jest to 28.x and bump TypeScript to 4.3.0

.github/workflows/build-lint-test.yml, .github/workflows/create-release-pr.yml, .github/workflows/publish-release.yml, .github/workflows/require-additional-reviewer.yml
This PR bumps the GitHub actions that we we use to the latest version, removing deprecation notices from our CI.
Similar to https://github.com/MetaMask/snaps-monorepo/pull/853
=> Bump actions

.github/workflows/create-release-pr.yml, .github/workflows/publish-release.yml, .github/workflows/scripts/update-major-version-tag.sh
re: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
continuation after missing some things in #98
=> Remove `set-output`

dist/index.js, package.json, yarn.lock
I'm still seeing a `set-output` deprecation in ci after the most recent bump :upside_down_face: 
This is because there is a `setOutput` call in `actions/core` that's been updated in https://github.com/actions/toolkit/pull/1178
So this bump takes care of that. I've also tested this in my fork and the deprecation notice is now gone.
=> Bump `@actions/core`

.github/workflows/build-lint-test.yml, dist/index.js, src/package-operations.ts
This pull request modifies the `getUpdatedDependencyField` function to avoid overriding the dependencies that should not
be updated. The update process should ignore certain dependencies that are used across multiple packages in a workspace.
The change involves introducing a check for the presence of `workspace:^` in the `package.json` file before updating
the version. This is an important step because `workspace:^` should not be overridden with new version ranges. The rest
of the dependency versions can be updated, however.
1. Added a check for `workspace:^` in `getUpdatedDependencyField` that prevents updating the version range for this dependency.
=> Check for `workspace:^` before replacing the version in package.json

package.json, src/package-operations.test.ts, src/package-operations.ts, yarn.lock
MetaMask/auto-changelog#155 adds a method to format changelogs using Prettier. I've enabled this option here.
This is a breaking change, since it will change the default formatting of the changelog in new release PRs. Packages updating to the next version of this package should simultaneously enable the `--prettier` flag on `auto-changelog`.
- The default formatting of the changelog will change.
- For this to be properly linted, [`auto-changelog` should be updated to run with the `--prettier` flag](https://github.com/MetaMask/metamask-module-template/pull/219/commits/29f1b97089f468461680f326c3b6ae3fb0f99a17).
=> BREAKING: Format changelog using Prettier
